### ISSUE TITLE
Duplexer confusing example

### ISSUE THREAD

**Issue by Rybadour** [workshopper/stream-adventure#104]
I'd recommend changing the challenge to use anything else but child_process. Seeing stdin and stdout as the arguments can give people false confidence of duplexer. I just spend an hour trying to figure out the next challenge only to find out that the order of duplexer is Writable, Readable. I know the documentation says that but other people made the same mistake: https://github.com/substack/stream-adventure/issues/55

I'd bet it help other people too if this challenge used process.stdin/stdout instead or something like reading from files.

**Comment by lyzadanger** [comment]
+1 on this. The confusing element for me here isn't `duplexer`'s argument order necessarily (which are explicitly mentioned in the instructions), but that `child_process.stdin` is a *Writeable* stream (as opposed to `process.stdin`, which is a *Readable* stream) and `child_process.stdout` which is likewise flipped from `process.stdout`. So I struggled for a while with

`return duplexer(childProcess.stdout, childProcess.stdin);`

Because I didn't realize that `child_process` flipped the `stdin/stdout` stream types (not because I didn't grok that the `Writeable` should come first).

At the very least perhaps a heads up to this little twist in `child_process`?

**Comment by Ryan1729** [comment]
I also found myself confused as to why 

``` return duplexer(childProcess.stdout, childProcess.stdin); ```

didn't work.

**Comment by famousgarkin** [comment]
+1

**Comment by Sequoia** [comment]
the confusion here stems from the following:

* `process.stdin`: :book: **Readable** stream
* `process.stdout`: :memo:  **Writable** stream
* `childProc.stdin`: :memo:  **Writable** stream
* `childProc.stdout`: :book: **Readable** stream

for process you're *inside* the process to `stdin` is readable to you, for child process you're *outside* so that process's `stdin` is writable to you.

**Comment by klarkc** [comment]
+1 The @Sequoia explanation must be in the documentation.

**Comment by mganuci** [comment]
Thank you @Sequoia  for the explanation, I got confused as well. However, event the reference solution doesn't work due to a unit test failing

```
not ok 3 should be equal
  ---
    operator: equal
    expected:
      'ihrl\nibza\nipzjbpa\nillasl\nillasl\nihghhy\nivvw\nillw\nillw\nibza\nibn\
nilla\nifghuapul\nive'
    actual:
      'ihrl\nibza'
  ...
```

**Comment by kalinchernev** [comment]
Nice discussion, definitely worth having the explanation from @Sequoia in the exercise to be accessible to anyone going through the problem. Opened a PR to include these additions in the hints.

**Comment by ccarruitero** [comment]
Closing since changes was added in #196
