### ISSUE TITLE
 Concat example : extra '\n' in output desireable?

### ISSUE THREAD

**Issue by scomp** [workshopper/stream-adventure#14]
The console.log() adds a '\n' to the output:

var concat = require('concat-stream');

process.stdin.pipe(concat(function (src) {
    var s = src.toString().split('').reverse().join('');
    console.log(s);
}));

Maybe this should be: 

var concat = require('concat-stream');
process.stdin.pipe(concat(function (src) {
    var s = src.toString().split('').reverse().join('');
    process.stdout.write(s);
}));

Thoughts?

**Comment by max** [comment]
+1

**Comment by ccarruitero** [comment]
I'm closing this since concat solution was updated to use `process.stdout.write` in https://github.com/workshopper/stream-adventure/commit/a2fd01a6ce0353874837f2021d6e709c3f21f06d, the problem description was updated to be more clear about `concat-stream` and what return in https://github.com/workshopper/stream-adventure/commit/6bcb76793e5fb2c5231c5e45d69afe3a55c9cf82

Also there will be an exercise about writable streams (#240) for complement the doubts about using that.
