### ISSUE TITLE
Create labels for issues?

### ISSUE THREAD

**Issue by ghost** [workshopper/stream-adventure#152]
I was thinking that it could be a good idea to use labels to specify what question a student is having problems with.  That way you can group all questions and get a clearer idea on what questions are more troubling than others. Does that make sense?

**Comment by kalinchernev** [comment]
@TSchnaars I started organizing issues and pull requests with labels indeed. So far, I started with general things, but have the feeling that at some points a label per problem might be useful to sort all things related to a given problem. However, I also notice that sometimes 2 problems are overlapping in the issues around them, and that's why I didn't label per problem. 

Ideas are welcome!

**Comment by ccarruitero** [comment]
Closing since labels was created
