### ISSUE TITLE
could you provide a way to localize ?

### ISSUE THREAD

**Issue by the6thm0nth** [workshopper/stream-adventure#161]
Hi, I'm hoony from Korea.

Could you let me know how to localize this project like i18n?

**Comment by kalinchernev** [comment]
Hi @6thmonth I think it'd definitely possible after some refactoring of the core framework of the workshopper.

I googled a bit on the subject and found that [discussion around i18n](https://github.com/nodeschool/organizers/issues/64) which lead me to see that there is a new framework [workshopper-adventure](https://github.com/workshopper/workshopper-adventure), which provides the means to make the workshopper translatable. For example, I opened [the main file of the learnyounode](https://github.com/workshopper/learnyounode/blob/master/learnyounode.js) workshopper which integrates the workshopper-adventure framework.

I'd treat this issue as a feature request, which would lead to refactoring of the main module to depend on the new workshopper-adventure framework. Then the translations will be possible via normal pull requests giving translation files.

CC @martinheidegger

**Comment by 6thmonth** [comment]
that's great news :) I'll looking forward to do that, thanks!

best

hoony

===============

const me = {

  “name_en”: “Hoony Chang”,

  “name_kr”: “춘식”,

  “type”: ["civic hacker”, “freelancer”],

  “language”: [“javascript”],

  “sports”: [“basketball”],

  “contact”: {

    “email_private”: “6thmonth@protonmail.ch”,

    “email_public”: “hoonch3@gmail.com”,

    “github”: “@6thmonth”,

    “twitter”: “@6thmonth__"

  }

}

On Sun, 06 Nov 2016 at 01:06 Kalin Chernev

<
mailto:Kalin Chernev <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi
https://github.com/6thmonth
I think it'd definitely possible after some refactoring of the core framework of the workshopper.

I googled a bit on the subject and found that
https://github.com/nodeschool/organizers/issues/64
which lead me to see that there is a new framework
https://github.com/workshopper/workshopper-adventure
, which provides the means to make the workshopper translatable. For example, I opened
https://github.com/workshopper/learnyounode/blob/master/learnyounode.js
workshopper which integrates the workshopper-adventure framework.

I'd treat this issue as a feature request, which would lead to refactoring of the main module to depend on the new workshopper-adventure framework. Then the translations will be possible via normal pull requests giving translation files.

CC
https://github.com/martinheidegger

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/workshopper/stream-adventure/issues/161#issuecomment-258621155
, or

**Comment by substack** [comment]
I don't get what workshopper-adventure is for, it seems like a bad idea. It should be possible to do localization without using a library which concatenates two other libraries for some reason.

**Comment by kalinchernev** [comment]
I just didn't find any other clue or documentation on the way :)
Should there be one, please share.

**Comment by martinheidegger** [comment]
@substack It was quite some work to properly translate workshoppers, including extensive work in regards to double-width characters and whatnot. In the interest of maintainability I would welcome if all workshoppers use workshopper-adventure (note: workshopper-adventure _should_ be API compatible (if it isn't -> issue)

**Comment by ccarruitero** [comment]
Closing this, since we are using now `workshopper-adventure` that come with `i18n` included.
