### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/stream-adventure#182]
Hello @substack,

I am trying to improve the workshoppers that are presented in NodeSchool and I am seeing a lot of PR's and issues in `stream-adventure`. `stream-adventure` is one of the most interesting tutorials of NodeSchool and I am wondering if you need help with maintaining it?

**Comment by BerniceChua** [comment]
Hi @substack & @martinheidegger, that's a great idea.  At this time, I'm still trying to learn, so I can't tell if the tests aren't passing because I did something wrong, or because of a bug in the test itself.  

I would like to help maintain this too, but in order for me to do that, what resources do you recommend for me to use?  Thanks in advance.

**Comment by kalinchernev** [comment]
I also hit the wall early on and got frustrated with simple things not working, so I came to notice the number of issues and pull requests.

@substack would it help if I you have at least someone to make review on these requests and issues and label them? (i.e. having someone to help without merging)

**Comment by martinheidegger** [comment]
@kalinchernev stream-adventure now moved to the workshopper organization.
I am very busy with some other task at the workshopper org atm. but my next task is definitely to update other out-dated workshoppers (such as this one). You can speed this up by joining the org (to which i just invited you!)

**Comment by kalinchernev** [comment]
Hi @martinheidegger thanks for the invite!
I can now go through the issue queue and "triage" when I can to help in the process.
Is there any convention for the labelling I should follow on the way?

**Comment by martinheidegger** [comment]
@kalinchernev Not at the moment. Please triage at free will.

**Comment by jpls93** [comment]
@martinheidegger @kalinchernev I am also interested in helping the development and maintenance of these tutorials. May I have instructions on where am I needed, or what I need to do?

**Comment by martinheidegger** [comment]
@jpls93 There is no one in charge of coordinating this effort (yet?) What do you think should be tackled first? _(My next task on the list would be to move from `adventure` to `workshopper-adventure`)_

**Comment by kalinchernev** [comment]
Hi,
I also don't know if anyone is in charge. After spending some time with the repo, things are not as bad as they seem on first sight. 

Shortly, the situation is more or less as following:

- Few [pull requests await attention](https://github.com/workshopper/stream-adventure/issues?q=is%3Aissue+is%3Aopen+label%3A%22PR+suggested%22) from someone who can say yes/no and merge
- There are several issues that I can personally confirm ([marked as bug](https://github.com/workshopper/stream-adventure/issues?q=is%3Aissue+is%3Aopen+label%3Abug))
- Few [questions asked](https://github.com/workshopper/stream-adventure/issues?q=is%3Aissue+is%3Aopen+label%3Aquestion), but always being bugs

There are also few new issues which are not categorized yet, so the same triaging can be applied to them. I think there are tasks for anyone interested into contributing, like answering questions and adding some guidelines. (I personally opened few pull requests adding guidelines for things that were problematic for me and I found suggested by issues)

Most importantly, I think, the non-stale pull request could be merged or given feedback to, in order to handle the issues which are already solved.

About migrating to `workshopper-adventure`, I am interested into working on this. If I know a potential pull request would be reviewed, it'd be also a good learning contribution.

**Comment by martinheidegger** [comment]
Hi @kalinchernev I made you team maintainer for the time being of stream-adventure-leads team. 😉  I don't think I ever tried to update stream-adventure to workshopper-adventure but i found an `fr` fork https://github.com/deliciousinsights/stream-adventure/tree/l10n-fr (if that helps)

**Comment by kalinchernev** [comment]
@martinheidegger thanks, I'm honored! :)
The fork could be a good base for having the first translation. #161 is also related to this.
@jpls93 what would you be interested into?

**Comment by kalinchernev** [comment]
@martinheidegger I started merging the low-hanging fruits which include clarifications in the problems' definitions. I think it'd be a good idea to make a release to npm after this.
What is the procedure for publishing releases?

**Comment by jpls93** [comment]
@kalinchernev @martinheidegger

Hello. I'm sorry I'm only speaking from a beginner's point of view. I'm not sure if my points are valid.

I understand that one of the challenges in developing these workshops is the level of knowledge to assume on a user who will be installing and going through the workshops. Forgive me if my position is weak since I'm only basing on introspection. It just makes me think that these workshops are created at all, to focus on beginners' user experience. 

For example, in `stream-adventure`, I found it intimidating to have the workshop assume that I know about importing modules (e.g. `fs`), or what `process.argv[2]` is. I know that diligence on a user would eventually lead to the [docs](https://nodejs.org/api/), or even [these](https://docs.npmjs.com/cli/install) [links](https://docs.npmjs.com/files/folders) should they find the installation process bewildering.

I am note sure how to efficiently tackle the challenge I have raised above. So, I decided to just start the process of developing a personal website to write articles/tutorials which would attempt to address them.

Thanks!

**Comment by kalinchernev** [comment]
Hi @jpls93 I personally think that "beginner" point of view, as you say, is a useful thing. I also still find many of the challenges intimidating as I'm coming from the PHP world where I've never seen or used streams before. So, similarly as you I went through the issue queue and pull requests while working on the adventure itself. (And I also jotted [some thoughts](https://medium.com/@kalin.chernev/triage-stream-adventure-issue-queue-3b60c9be0d60#.g1hoohvf8) in the process)

Contributing is much [more than writing sophisticated code](https://opensource.guide/how-to-contribute/#what-it-means-to-contribute) on github etc ;)

If you're interested, you can be helpful with things like:
- going through the list of [pull requests](https://github.com/workshopper/stream-adventure/pulls) and giving a thumbs up or feedback about things suggested. For example, i have opened few pull requests myself and it'd be really helpful for a second person to have a saying there
- you can also work through the issue queue: both creating new items for feeback you feel after making the challenges and replying to questions you know the answer to

At any case, I encourage you to give feedback and suggestions while you're making the challenges, as this is the best way to relate to the communication around the repo.

**Comment by martinheidegger** [comment]
> What is the procedure for publishing releases?

1. You need permissions to publish the workshopper. @workshopper/deploy  should have permission but it seems like that has not been given yet. @julianduque Would you mind to give @kalinchernev access to the repo?
2. There is no org-wide release policy _(we could setup a recommendation doc?!)_. However I try to have [signed commits](https://help.github.com/articles/signing-commits-using-gpg/) and use [standard-version](https://www.npmjs.com/package/standard-version) but that is my personal preference.

**Comment by kalinchernev** [comment]
@martinheidegger thanks, I see the topic is more global so I'll place some comments in the main thread of the @workshopper/deploy

**Comment by julianduque** [comment]
I gave write permissions to @kalinchernev on this repo

**Comment by ccarruitero** [comment]
This thread is outdated, and was resolved in that time. Closing now
