### ISSUE TITLE
remove request dependency

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/stream-adventure#232]
[request](https://www.npmjs.com/package/request) is deprecated

These dependency is used only in `http_client` exercise.
I think we should use [`http.request`](https://nodejs.org/api/http.html#http_http_request_options_callback) instead

**Comment by jordanSu** [comment]
I think we can do that.
I wrote the code below, and it passed the existing test without having to modify the test.
```js
const http = require('http');

const options = {
    hostname: 'localhost',
    port: 8099,
    method: 'POST'
}
const req = http.request(options, (res) => {
    res.on('data', (chunk) => {
        process.stdout.write(chunk);
    });
});

process.stdin.pipe(req);
```
I am thinking that is it possible for http module to pipe directly from stdin to stream then to stdout as below (something like `process.stdin.pipe(req).pipe(process.stdout)`)?

Because I think it would better describe the concept of stream.
If I understand the http module correctly, it seems not possible to do the same trick here.
What do you think?

**Comment by ccarruitero** [comment]
Hi @jordanSu 

Thanks for take a look into this. Do you mind start a PR for this?

You can't pipe `http.request()` directly to `stdout` since `http.request()` give you a [`http.ClientRequest`](https://nodejs.org/api/http.html#http_class_http_clientrequest), that is a writable stream; and you need to pipe from a redable stream or a duplex.
Instead you could pipe the `response` of the request to `stdout`.
 ```js
const req = request('http://localhost:8099', { method: 'POST' }, (res) => res.pipe(process.stdout))

process.stdin.pipe(req)
```

**Comment by jordanSu** [comment]
Hi @ccarruitero 
I start a PR #236 for this issue.

Please help review it, and any advice is welcome, especially the problem description part.

**Comment by ccarruitero** [comment]
fixed in https://github.com/workshopper/stream-adventure/commit/938de21f89a2a26665fc471a86aaf3559302d94a
