### ISSUE TITLE
duplexer-redux uses [object Object]

### ISSUE THREAD

**Issue by TimvdEijnden** [workshopper/stream-adventure#246]
I'm debugging this exercise and see something strange, see the screenshot below.
I'm using node 10.21.0

<img width="1404" alt="Screenshot 2020-07-06 at 20 08 03" src="https://user-images.githubusercontent.com/951290/86625091-c9e5d780-bfc4-11ea-9bb0-41ef1e1c1b73.png">

This solution is accepted but results in:

    {undefined: 73}

Which is not what should happen.

**Comment by ccarruitero** [comment]
Thanks @TimvdEijnden for notice this.

I found that the problem comes when we send the message to stdin.
https://github.com/workshopper/stream-adventure/blob/543d4bd8d3ad2757fab8dc2f864b59d737fa7560/lib/stdinProcessor.js#L4

Since we are sending an object in this exercise, adding the separator become in the string `[object Object]`

I'll open a PR to fix that
