### ISSUE TITLE
question about concat

### ISSUE THREAD

**Issue by franklingu** [workshopper/stream-adventure#48]
var concat = require('concat-stream');
var reverse = concat(function (buf) {
            var body = buf.toString().split('').reverse().join('');
            console.log(body);
         });

process.stdin.pipe(reverse).pipe(process.stdout);

the above is my program and I receive this error:
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at Pipe.onread (net.js:556:19)

any idea why and how to fix this?

**Comment by ccarruitero** [comment]
I'm closing this since concat solution was updated to use `process.stdout.write` in https://github.com/workshopper/stream-adventure/commit/a2fd01a6ce0353874837f2021d6e709c3f21f06d, the problem description was updated to be more clear about `concat-stream` and what return in https://github.com/workshopper/stream-adventure/commit/6bcb76793e5fb2c5231c5e45d69afe3a55c9cf82

Also there will be an exercise about writable streams (#240) for complement the doubts about using that.
