### ISSUE TITLE
HTTP STREAM problem does not explain that you must output the results to stdout

### ISSUE THREAD

**Issue by jordanbtucker** [workshopper/stream-adventure#66]

**Comment by kalinchernev** [comment]
Current problem description "Your program will get some html written to stdin. Convert all the inner html to
upper-case for elements with a class name of "loud", and pipe all the html to stdout."
Fixed in [this commit](https://github.com/workshopper/stream-adventure/commit/9604df2cfcab9daf1441938b2f1f430bc3f61b69)
